config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [] do
    collection do
    end
    member do
      get :show
      get :image
      get :preview_image
      get :images
      post :start
      get :play
      put :input
      get :finished
    end
  end

  get '/line/preview_image'   => 'linebot#preview_image'
  get '/line/image'           => 'linebot#image'
  get '/image'                => 'linebot#image'
  post '/callback'            => 'linebot#callback'

  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/user.rb
require 'fileutils'
include FileUtils

class User < ApplicationRecord

  STATE_IDLE = "idle"
  STATE_STARTED = "started"
  STATE_FINISHED = "finished"

  has_many :images, dependent: :destroy

  def col_numbers
    (col_numbers_str || "").split(',').map(&:to_i)
  end
  
  def col_numbers= numbers
    self.col_numbers_str = numbers.map(&:to_s).join(',')
  end
  
  def row_numbers
    (row_numbers_str || "").split(',').map(&:to_i)
  end

  def row_numbers= numbers
    self.row_numbers_str = numbers.map(&:to_s).join(',')
  end
  
  def answers
    (answers_str || "").split(',').map(&:to_i)
  end

  def answers= numbers
    self.answers_str = numbers.map(&:to_s).join(',')
  end
  
  def inputs
    (inputs_str || "").split(',').map(&:to_i)
  end

  def inputs= numbers
    self.inputs_str = numbers.map(&:to_s).join(',')
  end


  # 問題開始
  def start
    self.level = 2
    n = self.level
    q = 2.times.map{|i| n.times.map{|i| (1..9).to_a.sample}}
    self.col_numbers = q.first
    self.row_numbers = q.last

    a = []
    self.row_numbers.each do |r|
      self.col_numbers.each do |c|
        a << r + c
      end
    end
    self.answers = a

    self.images = []
    self.inputs = []

p self
    self.save
  end

  def input number
    return if finished?
    self.inputs = self.inputs + [number]
    self.save
  end

  def correct? at=nil
    at ||= [self.inputs.size - 1, 0].max
    self.inputs[at] == self.answers[at]
  end

  def correct_all?
    self.inputs == self.answers
  end

  def finished?
    self.inputs.size >= self.answers.size
  end

  def image at=nil
    step = at || self.step
    step = step.to_i
    img = images.at(at || step).first
    return img if img

    gen_image
    img = Image.create(user_id: self.id, data: File.read(image_file_path(step)), step: at)
    self.images << img
    img
  end

  def gen_image no=nil
    no ||= self.step
    l = self.level
    len = 410
    w = h = (len-2) / (l + 1)
    x0 = y0 = (len-2 - (l + 1) * w) / 2 + 1
    color = '#000000'
    image = MiniMagick::Image.open(base_image_path)
    r0 = no / l
    c0 = no % l
    # 枠と現在の加算箇所に丸印をつける
    image.combine_options do |c|
      (l + 1).times{|y| 
        (l + 1).times{|x|
          #c.stroke = color
          c.fill '#ffffff'
          c.stroke '#000000'
          cmd = "rectangle #{x0 + w * x},#{y0 + h * y} #{x0 + w * x + w},#{y0 + h * y + h}"
          c.draw cmd
          if !finished? && (
             (y == 0 && (c0 + 1) == x) ||
             (x == 0 && (r0 + 1) == y) ||
             ((x == (c0 + 1)) && (y == (r0 + 1)))
            )
            cx = x0 + w * x + w / 2
            cy = y0 + h * y + h / 2
            cmd = "circle #{cx},#{cy} #{cx + w/3},#{cy+ h/3}"
            c.draw cmd
          end
        }
      }
    end
    
    # 問題の数字を書き込み
    fontsize = (w * 0.8).to_i
    col_numbers.each_with_index do |n, i|
      image.combine_options do |config|
        config.font font_path
        config.pointsize fontsize
        config.fill '#000000'
        #config.gravity 'Center'
        #config.annotate
        x_offset = -6
        config.draw "text #{x0 + x_offset + (i + 1) * w + w / 2 - fontsize / 5},#{y0 + h - fontsize / 4} '#{n}'"
        config.draw "text #{x0 + x_offset+ w / 2 - fontsize / 5},#{y0 + (i + 2) * h - fontsize / 4} '#{row_numbers[i]}'"
      end
    end

    # 回答を書き込み
    inputs.each_with_index do |n, i|
      i = i.to_i
      y = i / l + 2
      x = i % l + 1
      image.combine_options do |config|
        config.font font_path
        config.pointsize fontsize
        config.fill '#000000'
        #config.gravity 'Center'
        #config.annotate
        case n.to_s.length
        when 2
          x_offset = -38
        else
          x_offset = -15
        end

        unless finished?
          config.fill '#000000'
          config.stroke '#000000'
        else
          if correct?(i)
            config.fill '#00ff00'
            config.stroke '#000000'
          else
            config.fill '#ff0000'
            config.stroke '#000000'
          end
        end
        config.draw "text #{x0 + x_offset + x * w + w / 2 - fontsize / 5},#{y0 + y * h - fontsize / 4} '#{n}'"
      end
    end

    image.combine_options do |config|
      config.font font_path
      config.pointsize fontsize
      if finished?
        if correct_all?
          config.fill '#00ff00'
          config.stroke '#000000'
          config.draw "text 100,120 '正解'"
        else
          config.fill '#ff0000'
          config.stroke '#000000'
          #config.draw "text 50,120 '不正解'"
          config.draw "text 50,120 'おしい'"
        end
      end
    end

    image.write image_file_path
  end

  def step
    self.inputs.size || 0
  end

  def base_image_path
    './app/assets/images/masu.png'
  end

  def font_path
    "./app/assets/fonts/ZenOldMincho-Bold.ttf"
  end

  def image_file_path step=nil
    step ||= self.step
    path = "tmp/#{self.id}/result_#{step}.png"
    mkdir_p File.dirname(path)
    path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy image preview_image images start play input finished]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    case @user.state
    when User::STATE_IDLE
    when User::STATE_STARTED
      redirect_to play_user_path(@user)
    when User::STATE_FINISHED
      redirect_to finished_user_path(@user)
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def image
    step = params[:step] || @user.step
    step = step.to_i
    img = @user.image(step)
    send_data(img.data, filename: "image_#{@user.id}_#{step}.jpg", disposition: 'attachment')
  end

  def preview_image
    send_data(@user.image.data, filename: 'image.jpg', disposition: 'attachment')
  end

  def images
  end

  def start
    @user.start
    redirect_to play_user_path(@user)
  end

  def play
  end

  def input
    @user.input params['number'].to_i
    puts "*"* 80, params['numbrer'].to_i
    if @user.finished?
      redirect_to finished_user_path(@user)
    else 
      redirect_to play_user_path(@user)
    end
  end

  def finished
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_id, :state)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/finished.html.erb
<%= image_tag image_user_path(@user) %>

<p><h1>
    <% if @user.correct_all? %>
        <font color='green'>
            正解
        </font>
    <% else %>
        <font color='red'>
            残念
        </font>
    <% end %>
</h1></p>

<%= link_to 'スタート', start_user_path(@user), method: :post %>

app/views/users/images.html.erb
<% @user.images.each_with_index do |img, i| %>
    <%= image_tag image_user_path(@user, step: i) %>
    <br />
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_id %></td>
        <td><%= user.state %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/input.html.haml
<%= form_with(url: input_user_url, method: :put) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/play.html.erb
<%= image_tag image_user_path(@user) %>


<%= form_with(url: input_user_url, method: :put) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'start', play_user_paty(@user) %>

<% if false %>
<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> -->
<% end %>